#!/usr/bin/env python3
import os
import sys
import subprocess

def hook(exc_type, exc_value, tb):
    print(f"\033[31m<{exc_type.__name__}>\033[0m: {' '.join(exc_value.args)}")
    sys.exit(1)

sys.excepthook = hook

exec = subprocess.call

QUIET=sys.stdout if "-q" not in sys.argv else subprocess.PIPE

PREFIX_DIR=os.path.join(os.getcwd(), "result")
DATA_DIR=os.path.join(PREFIX_DIR, "data")

r = False
if os.path.exists("build") is False or (r:="-r" in sys.argv) is True:
    args = ["meson", "build", f"-Dprefix={PREFIX_DIR}", f"-Ddatadir={DATA_DIR}"]
    if r is True:
        args.insert(2, "--reconfigure")
    exec(args, stdout=QUIET)

exec(["meson", "install"], cwd="build", stdout=QUIET)
if "-b" not in sys.argv:
    exec(["./result/bin/shell"])
